--------------------------------------------------------
--  File created - пятница-февраля-19-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANIES
--------------------------------------------------------

  CREATE TABLE "COMPANIES" 
   (	"COMPANY" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE), 
	 CONSTRAINT "COMPANIES_PK" PRIMARY KEY ("COMPANY") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "PAYMENTS" 
   (	"PAYMENT" NUMBER(*,0), 
	"DAY" DATE, 
	"COMPANY" NUMBER(*,0), 
	"SUM" NUMBER(*,2), 
	"PURPOSE" NUMBER(*,0), 
	"STATUS" NUMBER(*,0), 
	 CONSTRAINT "PAYMENTS_PK" PRIMARY KEY ("PAYMENT") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table PURPOSES
--------------------------------------------------------

  CREATE TABLE "PURPOSES" 
   (	"PURPOSE" NUMBER(*,0), 
	"TEXT" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PURPOSES_PK" PRIMARY KEY ("PURPOSE") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
REM INSERTING into COMPANIES
SET DEFINE OFF;
REM INSERTING into PAYMENTS
SET DEFINE OFF;
REM INSERTING into PURPOSES
SET DEFINE OFF;
